# Generated by Django 2.2 on 2020-04-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=models.TextField(max_length=750),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
